### ISSUE TITLE
全面屏截取照片不对

### ISSUE THREAD

**Issue by smj580** [DLTech21/ZXingCamera#1]
如题，截取照片会大于当前身份证的照片

**Comment by DLTech21** [comment]
大多少

**Comment by DLTech21** [comment]
@smj580 报一下手机型号

**Comment by smj580** [comment]
之前全面屏都有这个问题 解决了。。。请问一下 最近下载你的项目 编译后识别的时候crash 缺少so文件 但是我的gradle中找到了so文件 但是打包出来的apk中不包含那个so文件 问一下你遇到过这个嘛 用的是1.1.1 然后1.1.3直接打开识别直接crash 缺少另外一个so文件

**Comment by DLTech21** [comment]
你的armfilter配置了什么

**Comment by smj580** [comment]
abiFilters ‘armeabi’  但是我直接下载你的demo 安装后直接打开识别也crash 我没有改gradle 之前7月份提问的时候 那时候编译你的demo 可以直接运行识别

**Comment by DLTech21** [comment]
1.1.3是只支持armeabi-v7a

**Comment by smj580** [comment]
你的demo 下载下来直接依赖的是1.1.1 打开后 启动摄像头没问题  但是扫描身份证的时候crash 提示错误是
 couldn't find "libIDCardengine.so"
缺少so文件

**Comment by smj580** [comment]
请问有进展了嘛 如果方便的话 加一下qq？505968008 感谢

**Comment by DLTech21** [comment]
你用1.1.3，然后改armfilter为v7a就可以啦

**Comment by smj580** [comment]
大佬 可以了~感谢！
