### ISSUE TITLE
小米手机出现了崩溃，背面和正面扫码都是

### ISSUE THREAD

**Issue by AdminQQZ** [DLTech21/ZXingCamera#10]
![TIM截图20190314142221](https://user-images.githubusercontent.com/12959954/54335662-a88d0980-4664-11e9-8ce5-d937f0b908bd.png)

**Comment by DLTech21** [comment]
小米是有问题，在debug

**Comment by DLTech21** [comment]
更新代码 就可以用了，请注意ndk的架构
