### ISSUE TITLE
相机为啥掉不起来。。

### ISSUE THREAD

**Issue by darkSuperman** [DLTech21/ZXingCamera#2]
在手机上是好的，在一个平板上相机是黑屏的，日志打印报camera error 100，代码也不能修改，那里面的识别算法没开源吗？希望作者回复

**Comment by DLTech21** [comment]
什么平板

**Comment by darkSuperman** [comment]
杂牌的，就是 一块开发板，只有一枚后置摄像头的，相机ID应该是0，我用zxing扫码打开相机都是正常的

**Comment by DLTech21** [comment]
试试单纯引用compile 'io.github.dltech21:zcamera:1.0.3'
查看demo中的CameraActivity

**Comment by darkSuperman** [comment]
compile 'io.github.dltech21:idcard_ocr:1.1.1'
请问这个库也是你写的吗？

**Comment by DLTech21** [comment]
是的

**Comment by darkSuperman** [comment]
这个ocr识别库 IDCard idCard = IDDetectGo.getInstance().detect(activity, cropStream.toByteArray()) 就是这样用吗？传一张身份证照片的 byte[]就可以了吧。

**Comment by DLTech21** [comment]
可以的

**Comment by darkSuperman** [comment]
哦，多谢了
