### ISSUE TITLE
armeabi -v7a

### ISSUE THREAD

**Issue by devzwy** [DLTech21/ZXingCamera#5]
项目中用到了别的厂家的so,没有支持armeabi 这种架构，他们都是从armeabi  -v7a开始兼容的，有没有armeabi -v7a的动态库可以使用呢？

**Comment by DLTech21** [comment]
晚点更新吧

**Comment by devzwy** [comment]
> 晚点更新吧

感谢~，时刻关注中。辛苦楼主 @DLTech21

**Comment by DLTech21** [comment]
你要什么功能

**Comment by devzwy** [comment]
你好楼主，就是实时扫描的功能，然后身份证人相框可以加个人头像最好，或者能够自己拓展视图。现在公司项目比较着急的就是库能够支持v7a或者更高兼容。再次感谢楼主。

**Comment by devzwy** [comment]
@DLTech21 ### 坐等更新

**Comment by DLTech21** [comment]
更新了，看readme

**Comment by devzwy** [comment]
thank you~

> 更新了，看readme
